; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy_force

;--------------------------------------------------------------------------------------------------
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -Wno-unused-function
    -Wno-uninitialized
upload_protocol = teensy-cli
upload_port = COM9
monitor_port = COM9
monitor_speed = 9600
; change microcontroller
board_build.mcu = imxrt1062
; change MCU frequency
board_build.f_cpu = 600000000L
lib_deps =
    paulstoffregen/Encoder @ ^1.4.4
    ; waspinator/AccelStepper@^1.64
    bogde/HX711@^0.7.5
build_src_filter = +<main_67.2.cpp>

; -------------------------------------------------------------------------------------------------
[env:teensy_force]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -Wno-unused-function
    -Wno-uninitialized
upload_protocol = teensy-cli
upload_port = COM9
monitor_port = COM9
monitor_speed = 9600
board_build.mcu = imxrt1062
board_build.f_cpu = 600000000L
lib_deps =
    paulstoffregen/Encoder @ ^1.4.4
    bogde/HX711@^0.7.5
build_src_filter = +<main_67.2.cpp>





